<?php

namespace App\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DoubletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoubletRepository extends EntityRepository
{
    public function getdoubletbyequipe($id)
    {
        $query = $this->createQueryBuilder('d')
                ->where('d.equipe=:id')
                ->leftJoin('d.equipe', 'e')
                ->addSelect('e')
                ->setParameter('id',$id)
                ->getQuery()->getArrayResult();
        
        return $query;
    }
}
