# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /cookiepit
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            logout :
                target : /cookiepit
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/cookiepit$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/joueurs, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/tournoi, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/equipe, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/pays, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/ville, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/court, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/doublet, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/actualite, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/ , roles: ROLE_SUPER_ADMIN }
        - { path: ^/capitaine/ , roles: ROLE_ADMIN }