<?php

namespace App\UserBundle\Repository;

/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends \Doctrine\ORM\EntityRepository {

    public function findlistJoueurByEquipe($id) {
        $qb = $this->_em->getRepository('AppAdminBundle:Doublet')
                ->createQueryBuilder('d')
                ->leftJoin('d.joueurs', 'jd')
                ->select('jd.id')
                ->getQuery()
                ->getDQL();
        $params = ['id' => $id];
        $query = $this->createQueryBuilder('j');
        $res = $query->where('j.equipe = :id')
                        ->andWhere($query->expr()->notIn('j.id', $qb))
                        ->setParameters($params)
                        ->getQuery()->getArrayResult();
        $data = array();
        foreach ($res as $k => $v) {
            $data[$v['id']] = $v['nomPrenom'];
        }
        return $data;
    }

    public function getjouerbyequipe($id) {
        $query = $this->createQueryBuilder('j')
                        ->leftJoin('j.equipe', 'e')
                        ->where('e.id =:id')
                        ->setParameter('id', $id)
                        ->getQuery()->getArrayResult();
        return $query;
    }
    
    public function getdetailjoueurbydoublet($id)
    {
        $query = $this->createQueryBuilder('j')
                ->leftJoin('j.doublet', 'd')
                ->addSelect('d')
                ->leftJoin('j.equipe', 'e')
                ->addSelect('e')
                ->where('d.id=:id')
                ->setParameter('id', $id)
                ->getQuery()->getArrayResult();
        return $query;
    }
    
    public function getEquipe($id)
    {
        $query = $this->createQueryBuilder('j')
                ->leftJoin('j.equipe', 'e')
                ->addSelect('e')
                ->where('j.id=:id')
                ->setParameter('id', $id)
                ->getQuery()->getSingleResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        return $query;
        
    }

}
