type_notification_index:
    path:     /
    defaults: { _controller: "AppAdminBundle:Type_Notification:index" }
    methods:  GET

type_notification_show:
    path:     /{id}/show
    defaults: { _controller: "AppAdminBundle:Type_Notification:show" }
    methods:  GET

type_notification_new:
    path:     /new
    defaults: { _controller: "AppAdminBundle:Type_Notification:new" }
    methods:  [GET, POST]

type_notification_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppAdminBundle:Type_Notification:edit" }
    methods:  [GET, POST]

type_notification_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppAdminBundle:Type_Notification:delete" }
    methods:  DELETE
