<?php

namespace App\AdminBundle\Repository;

/**
 * DoubletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoubletRepository extends \Doctrine\ORM\EntityRepository
{
}
