<?php

namespace App\AdminBundle\Repository;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends \Doctrine\ORM\EntityRepository {

    function getEquipe($name) {
        return $query = $this->createQueryBuilder('e')
                        ->leftJoin('AppAdminBundle:Doublet', 'd', 'WITH', 'e.id=d.equipe')
                        ->addSelect('d')
                        ->where('e.libelle=:name')
                        ->setParameter('name', $name)
                        ->getQuery()->getArrayResult();
    }

    function getall() {
        $query = $this->createQueryBuilder('e')
                        ->getQuery()->getArrayResult();
        $data = [];
        foreach ($query as $k => $v) {
            $joueurs= $this->_em->getRepository('AppUserBundle:Joueur')
                    ->createQueryBuilder('j')
                    ->where('j.equipe=:id_equipe')
                    ->setParameter('id_equipe', $v['id'])
                    ->getQuery()->getArrayResult();
            $nombrejoueurexist = count($joueurs);
            $data[$k] = array('id'=>$v['id'],
                'libelle'=>$v['libelle'],
                'nbrjoueur'=>$v['nbrjoueur'],
                'adresse'=>$v['adresse'],
                'website'=>$v['website'],
                'mail'=>$v['mail'],
                'tel'=>$v['tel'],
                'joueur'=>$joueurs,
                'nombrejoueurexist'=>$nombrejoueurexist
                );
           
        }
        return $data;
    }
    
   

}
