<?php

namespace App\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JourneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourneeRepository extends EntityRepository
{
}
