<?php

namespace App\AdminBundle\Repository;

/**
 * RencontreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RencontreRepository extends \Doctrine\ORM\EntityRepository
{

    public function findrencontrebymatch($id){
        return $query = $this->createQueryBuilder('r')
            ->leftJoin('r.doublet1','d')
            ->addSelect('d')
            ->leftJoin('r.doublet2','d2')
            ->addSelect('d2')
            ->where('r.matchs=:id')
            ->setParameter('id',$id)
            ->getQuery()->getArrayResult();
    }
    
    public function getrencontrebyId($id)
    {
        return $query = $this->createQueryBuilder('r')
                ->leftJoin('r.matchs','m')
                ->addSelect('m')
                ->where('r.id=:id')
                ->setParameter('id', $id)
                ->getQuery()->getSingleResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
}
