<?php

namespace App\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreRepository extends EntityRepository
{
    public function getbyEquipe1($id)
    {
        $query = $this->createQueryBuilder('s')
                ->where('s.idEquipe1=:id')
                ->setParameter('id', $id)
                ->getQuery()->getArrayResult();
        return $query;
    }
    
    public function getbyEquipe2($id)
    {
        $query = $this->createQueryBuilder('s')
                ->where('s.idEquipe2=:id')
                ->setParameter('id',$id)
                ->getQuery()->getArrayResult();
        return $query;
    }
    
  
    
}
