<?php

namespace App\AdminBundle\Repository;

/**
 * TournoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournoiRepository extends \Doctrine\ORM\EntityRepository
{
    
    function gettournoi($id){
        $params=['id'=>$id];
        return $query = $this->createQueryBuilder('t')
                ->where('t.id=:id')
                ->setParameters($params)
                ->getQuery()->getSingleResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        
        
    }
}
