<?php

namespace App\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends EntityRepository
{
    public function getvillebyId($id)
    {
        $query = $this->createQueryBuilder('v')
                ->where('v.pays_id=:id')
                ->setParameter('id', $id)
                ->getQuery()->getArrayResult();
     
        return $query;
    }
    
    public function getall()
    {
        $query = $this->createQueryBuilder('v')
                ->leftJoin('AppAdminBundle:Pays','p','WITH','p.id=v.pays_id')
                ->addSelect('p')
                ->getQuery()->getResult(Query::HYDRATE_SCALAR);
        return $query;
    }
}
